### ISSUE TITLE
Use Dart Sass Implementation instead of Node SASS

### ISSUE THREAD

**Issue by Dreimus** [Oksydan/falcon#132]
Hello, 

Did you considered using [dart sass](https://sass-lang.com/dart-sass) instead of node sass implementation ?

It reduce compilation timing and assure a long term support for sass features.

Thanks

**Comment by Oksydan** [comment]
Hi @Dreimus,

Actually we moved from node-sass to dart sass in develop branch recently.
Dart sass performance is worse than node-sass but there is sass-embedded package that improves performance https://github.com/Oksydan/modern-prestashop-starter-theme/commit/e210f8bca400d8cb738db78790a806859f7873c8.

By default we are using sass instead of sass-embedded coz of CI I had implemented recently on dev branch. I will be trying to make CI working with sass-embedded.

**Comment by Dreimus** [comment]
Thanks for your feeback ! When do you think the v3 will be released ?

**Comment by Oksydan** [comment]
I am planning to release new version day after prestashop 8.0 release.

**Comment by Oksydan** [comment]
New version has been released. 
I am closing this issue.
