### ISSUE TITLE
Product Comments Module - Issue on variation change

### ISSUE THREAD

**Issue by Alan3k** [Oksydan/falcon#137]
Hello,

I have issue with product comments module. When I change product variant, stars on comment list are not refreshing. After reloading page everything is fine. Screenshots below:

![reviews](https://user-images.githubusercontent.com/29299511/198561209-12af3986-28d9-40ba-ac7a-26c8e8390602.jpg)
![combination](https://user-images.githubusercontent.com/29299511/198561200-050ec967-d412-494c-82ed-9070eac9adf0.jpg)
![reviews-2](https://user-images.githubusercontent.com/29299511/198561211-7498caab-ded8-4715-a430-d96c947885f9.jpg)

I think there is missing some function in list-comments.js file.
Tryied add some fixes by myself but no luck. Can you help with this function?

Thank you.

**Comment by Oksydan** [comment]
Hi @Alan3k,

Thank you for creating an issue.
Your problem is related to [this code](https://github.com/Oksydan/modern-prestashop-starter-theme/blob/master/modules/productcomments/views/js/list-comments.js#L42-L44).
You can fix it by creating more specific selector for that `'.grade-stars'` to not include comments list grades.
I will fix it in next version.

**Comment by Alan3k** [comment]
I have changed target selector to `'.comments-note .grade-stars'` and now after changing product variation, stars in comments list are displaying correct.

Thank you for help.

**Comment by Oksydan** [comment]
Hi @Alan3k,

It has been fixed on develop branch https://github.com/Oksydan/modern-prestashop-starter-theme/commit/e95ba2ec167088a5ce8fadb87ffd94d3fee598d9
It will be available in new version 3.0.0.

**Comment by Oksydan** [comment]
New version has been released. 
I am closing this issue.
