### ISSUE TITLE
Templates/partials/form-fields.tpl  Pattern in form_field_item_other does not allow ending with a space

### ISSUE THREAD

**Issue by sparh** [Oksydan/falcon#145]
Hello
in the form-fiels template for form_field_item_other you use this pattern :  pattern="^[^\s]+(\s+[^\s]+)*$ but if the user input has a space at the end of the input it will be denied.
Maybe you should allow space at the end of the string

regards and thanks for the theme

**Comment by fuchsbart** [comment]
Hi @sparh,

the problem can also be solved by trimming the input before validation.

`  $("input[type=text]").on('blur', function () {
    $(this).val($(this).val().trim());
  });`

**Comment by Oksydan** [comment]
Hi @sparh and @fuchsbart,

@sparh thank you for creating an issue. We are really close to release 3.0.0 I don't want to do any changes atm.
Solution provided by @fuchsbart is ok IMO but instead of this use `event.currentTarget` 😄.
Thank you @fuchsbart for your help. 
I will consider adding it in next version.

**Comment by Oksydan** [comment]
Hi @sparh 

new version has been released.
I am closing this issue.
