### ISSUE TITLE
🐛 [BUG] - is_themecore configuration problems with multi store

### ISSUE THREAD

**Issue by cruftex** [Oksydan/falcon#193]
### Description

PerstaShop 8.0.1
Multi Store enabled

### Node.js version

I did not install node

### php version

8.1.2

### OS and it's version

Ubuntu 22.04

### Browsers

Chrome

### Required module/theme

is_themecore

### Reproduction steps

```bash
With "All shops" context I press "Configure" and get the error:
> The module is_themecore is inactive.

When I select a individual shop the configure screen appears, however, there is an additional unaligned checkbox.

![Screenshot_20230227_172617_is-themecore-multistore](https://user-images.githubusercontent.com/2668191/221526866-95a38859-ae01-4e16-803d-1b20c2774b46.png)

When I try to enable WEPB, it seems not to save the settings. When I display the form again, it is disabled.
```

**Comment by Oksydan** [comment]
Hi @cruftex,

new version has been released and this problem has been fixed.
There are two new version:
 - for prestashop 8.0 - 3.0.2,
 - for prestashop < 8.0 - 2.3.2
 
BTW about that unaligned checkbox. The problem is coming from prestashop itself. I was able to reproduce an issue but I didn't fix it. Whole form is being generated by `form_widget` function that is using prestashop_ui_kit. I am not styling anything there.

Thank you for your report.

**Comment by cruftex** [comment]
@Oksydan Thanks for looking into this!

When I select one store I can save the settings now. However, when I select "All shops" it says still:

> The module is_themecore is inactive.

Now the situation is: I can set quality to 80 in one store and quality to 60 in another store. But I guess the webp generation is not specific to one store, is it?

Is it somehow possible that the setup is working with "All shops"? Ideally the setting would also not work on an individual store basis, since this isn't supported internally, e.g. by generating different webp files.

I can see that other modules have the same issue with the multi store environment, e.g. ps_linklist is also saying "inactive" upon configure when "All shops" is selected.
