### ISSUE TITLE
🐛 [BUG] - Operation is insecure

### ISSUE THREAD

**Issue by radioaktywnyyPL** [Oksydan/falcon#223]
### Description

Hi. Today I decided to use this template. The installation went smoothly. After typing the last "yarn dev" command, I enabled the store and saw these errors. I can't remove it. Can someone help me? Thanks in advance!

![Bez tytułu](https://user-images.githubusercontent.com/132513697/236054178-c4286c68-5243-41c0-b127-dd435deaa06b.png)

### Node.js version

v18.1.0

### php version

v7.4

### OS and it's version

Ubuntu 22.04

### Browsers

Firefox

### Required module/theme

theme

### Reproduction steps

```bash
1. Go to 'mystep.pl'
2. See error
```

**Comment by Oksydan** [comment]
Hi @radioaktywnyyPL,

looks like you are trying to use webpack dev server in production mode.
You shouldn't do it in your production servers. 

I didn't take into consideration https in project-init script. It always create SITE_URL inside .env file with http protocol.
Please go to `/themes/falcon/_dev/webpack/.env` and change that `http://mystep.pl` into `https://mystep.pl`.
If you would like to build it for production you should run `yarn build` instead of `yarn dev`.

**Comment by radioaktywnyyPL** [comment]
Thats work, thanks!

I don't know much about styles, but I would like to change two things. On the template demo, the categories are nicely arranged in a line of 3 products. However, there are 2 in my store. I tried to change the product-list-grid in theme.css, but when I change the value to 33.333333%, it's ok on PC, but everything goes wrong on mobile. How to make 3 products in line for PC and 2 products for mobile?

Can I disable sticky header on PC? I have a lot of subcategories and the sticky header is blocking some of them. On mobile it's ok.

Thank you very much for help!

**Comment by Oksydan** [comment]
Hi @radioaktywnyyPL,

We are not providing here solutions for changing stuff in theme. 
If you would like to changes something you should already knew js/scss and webpack tool to do it yourself. 
If you don't have enough knowledge there are plenty of free courses and online resources to read.  
If you don't want to learn it, just hire someone to do it for your. 

Since this issue has been resolved, I am closing this issue.
If you encounter a problem, you can open a new issue.
